# Generated by Django 2.2 on 2019-04-21 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190420_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
