# Generated by Django 2.2 on 2019-04-21 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190421_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortened',
            name='url_shortened',
            field=models.CharField(max_length=256, null=True, unique=True),
        ),
    ]
