# Generated by Django 2.2 on 2019-04-26 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190421_0141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15)),
                ('locale', models.CharField(max_length=256)),
                ('date_hour', models.DateTimeField(auto_now_add=True)),
                ('browser', models.CharField(max_length=256)),
                ('os', models.CharField(max_length=256)),
                ('shortened', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shorteneds', to='app.Shortened')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='app.Perfil')),
            ],
        ),
    ]
