# Generated by Django 2.2 on 2019-04-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_click'),
    ]

    operations = [
        migrations.AlterField(
            model_name='click',
            name='browser',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='click',
            name='ip',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='click',
            name='locale',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='click',
            name='os',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
