# Generated by Django 2.2 on 2019-04-26 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190426_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='click',
            name='shortened',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='app.Shortened'),
        ),
    ]
