# Generated by Django 2.2 on 2019-04-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_shortened_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortened',
            name='preview_message',
            field=models.TextField(null=True),
        ),
    ]
