# Generated by Django 2.2.1 on 2019-07-30 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_shortened_preview_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortened',
            old_name='url',
            new_name='url_user',
        ),
    ]
